#!/usr/bin/env python3
"""Builds FarmingData.kt from RuneLite's time-tracking plugin (BSD 2-Clause).

Usage: convert_farming.py <runelite checkout> <output .kt>
Reads timetracking/farming/Produce.java: each crop's patch type, minutes per growth tick and
number of stages (planted .. fully grown).
"""
import re, sys

SKIP_PATCHES = {"COMPOST", "BIG_COMPOST"}
SKIP = {"ANYHERB"}


def main():
    root, out = sys.argv[1], sys.argv[2]
    src = open(root + "/runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/Produce.java").read()
    rows = []
    for m in re.finditer(r'^\s*(\w+)\("([^"]+)",\s*(?:(-?\d+),\s*)?(?:PatchImplementation\.(\w+),\s*)?ItemID\.\w+,\s*(\d+),\s*(\d+)(?:,\s*(\d+),\s*(\d+))?\)', src, re.M):
        enum, name, _, patch, tick, stages, regrow, harv = m.groups()
        if patch is None or patch in SKIP_PATCHES or enum in SKIP:
            continue
        rows.append((name, patch, int(tick), int(stages)))
    with open(out, "w") as fh:
        fh.write("package com.questoverlay.farming\n\n")
        fh.write("// Generated by tools/convert_farming.py from RuneLite's time-tracking plugin\n")
        fh.write("// (BSD 2-Clause, Copyright (c) 2018 Abex, NotFoxtrot). Do not edit by hand.\n\n")
        fh.write("internal val CROP_TABLE: List<Crop> = listOf(\n")
        fh.write(",\n".join(f'    Crop("{n}", Patch.{p}, {t}, {s})' for n, p, t, s in rows))
        fh.write("\n)\n")
    print(f"{len(rows)} crops -> {out}")


if __name__ == "__main__":
    main()
